//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUENTA()
        {
            this.FACTURA = new List<FACTURA>();
        }
    
        public int IDCUENTA { get; set; }
        public int IDROL { get; set; }
        public int IDPERSONA { get; set; }
        public string EMAILCUENTA { get; set; }
        public string USUACUENTA { get; set; }
        public string CONTRACUENTA { get; set; }
        public Nullable<System.DateTime> FECHARESGISTROCUENTA { get; set; }
        public Nullable<short> ACTIVOCUENTA { get; set; }
    
        public virtual ROL ROL { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<FACTURA> FACTURA { get; set; }
    }
}
