//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEVENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLEVENTA()
        {
            this.VENT_ITEM = new List<VENT_ITEM>();
        }
    
        public int IDVENTA { get; set; }
        public int IDFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAVENTA { get; set; }
        public string FORMAPAGOVENTA { get; set; }
        public string ESTADOPAGOVENTA { get; set; }
        public Nullable<decimal> DESCUENTOVENTA { get; set; }
        public Nullable<decimal> IVAVENTA { get; set; }
        public Nullable<decimal> SUBTOTALVENTA { get; set; }
        public Nullable<decimal> TOTALVENTA { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<VENT_ITEM> VENT_ITEM { get; set; }
    }
}
