//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLEITEM()
        {
            this.PRODUC_ITEM = new List<PRODUC_ITEM>();
            this.VENT_ITEM = new List<VENT_ITEM>();
        }
    
        public int IDDETALLEITEM { get; set; }
        public string DESCRIPITEM { get; set; }
        public Nullable<int> CANTIITEM { get; set; }
        public Nullable<decimal> PUNITITEM { get; set; }
        public Nullable<decimal> PTOTALITEM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<PRODUC_ITEM> PRODUC_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<VENT_ITEM> VENT_ITEM { get; set; }
    }
}
