//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONA()
        {
            this.CUENTA = new List<CUENTA>();
        }
    
        public int IDPERSONA { get; set; }
        public string NOMPERSONA { get; set; }
        public string APEPERSONA { get; set; }
        public string IDENTIPERSONA { get; set; }
        public Nullable<int> TELPERSONA { get; set; }
        public string DIRREPERSONA { get; set; }
        public string PAISPERSONA { get; set; }
        public string CIUPERSONA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<CUENTA> CUENTA { get; set; }
    }
}
