//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.PRODUC_ITEM = new List<PRODUC_ITEM>();
        }
    
        public int IDPRODUCTO { get; set; }
        public int IDPROVEEDOR { get; set; }
        public int IDCATEGORIA { get; set; }
        public string CODPRODUCTO { get; set; }
        public string NOMPRODUCTO { get; set; }
        public string MARCAPRODUCTO { get; set; }
        public string IMAGENPRODUCTO { get; set; }
        public Nullable<short> ACTIVOPRODUCTO { get; set; }
        public Nullable<int> STROCKPRODCUTO { get; set; }
        public string DESCRIPPRODUCTO { get; set; }
        public Nullable<decimal> PCOMPRAPRODUCTO { get; set; }
        public Nullable<decimal> PVENTAPRODUCTO { get; set; }
        public Nullable<System.DateTime> FECHAREGIDTROPRODUCTO { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<PRODUC_ITEM> PRODUC_ITEM { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
