//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.PRODUCTO = new List<PRODUCTO>();
        }
    
        public int IDPROVEEDOR { get; set; }
        public string RUCPROVEEDOR { get; set; }
        public string NOMPROVEEDOR { get; set; }
        public string EMAILPROVEEDOR { get; set; }
        public Nullable<int> TELPROVEEDOR { get; set; }
        public string PAISPROVEEDOR { get; set; }
        public string CIUPROVEEDOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<PRODUCTO> PRODUCTO { get; set; }
    }
}
