//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENT_ITEM
    {
        public int IDVENT_ITEM { get; set; }
        public int IDDETALLEITEM { get; set; }
        public int IDVENTA { get; set; }
    
        public virtual DETALLEITEM DETALLEITEM { get; set; }
        public virtual DETALLEVENTA DETALLEVENTA { get; set; }
    }
}
